<a href="https://colab.research.google.com/github/javilledo/machine-learning/blob/master/notebooks/t04_04_linear_regression_scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# REGRESIÓN LINEAL EN PYTHON
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

In [7]:
url_data = 'https://raw.githubusercontent.com/javilledo/python-ml-course/master/datasets/ads/Advertising.csv'
data = pd.read_csv(url_data)
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [13]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

In [9]:
feature_cols = ['TV', 'Radio', 'Newspaper']

In [10]:
x = data[feature_cols]
y = data['Sales']

In [14]:
estimator = SVR(kernel='linear')
selector = RFE(estimator, 2, step = 1) #me quiero quedar con 2 variables predictivas, en un paso
selector = selector.fit(x,y)

In [15]:
selector.support_ # indica qué variables son con las que se ha quedado

array([ True,  True, False])

In [25]:
pd.DataFrame(feature_cols)[selector.support_]

0
0     TV
1  Radio

In [26]:
selector.ranking_

array([1, 1, 2])

In [27]:
from sklearn.linear_model import LinearRegression

In [29]:
x_pred = x[['TV', 'Radio']]

In [30]:
lm = LinearRegression()
lm.fit(x_pred, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [31]:
lm.intercept_

2.921099912405138

In [32]:
lm.coef_

array([0.04575482, 0.18799423])

In [35]:
lm.score(x_pred,y) #es el valor de R2

0.8971942610828956